version: '3'

services:
  ollama:
    container_name: ollama
    image: ollama/ollama
    networks:
      mynetwork:
        ipv4_address: 172.18.0.2
    ports:
      - "11434:11434"

  open-webui:
    container_name: open-webui
    image: ghcr.io/open-webui/open-webui:main
    restart: always
    networks:
      mynetwork:
        ipv4_address: 172.18.0.3
    ports:
      - "6969:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - ollama

networks:
  mynetwork:
    name: GPT-network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
